### ISSUE TITLE
Does not compile on aarch64, ppc64le, ppc64

### ISSUE THREAD

**Issue by agrover** [stratis-storage/devicemapper-rs#328]
On some non-Intel, archs, devicemapper fails to compile, due to the changes in 69efb22f5a577. Unfortunately we don't (yet) have CI for these platforms, and it's not clear if these are bugs in our code or some other code.

```
error[E0308]: mismatched types
  --> src/deviceinfo.rs:59:25
   |
59 |             unsafe { &*(&self.hdr.name as *const [i8; DM_NAME_LEN] as *const [u8; DM_NAME_LEN]) };
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found array of 128 elements
   |
   = note: expected type `u8`
              found type `[i8; 128]`
error[E0308]: mismatched types
  --> src/deviceinfo.rs:69:25
   |
69 |             unsafe { &*(&self.hdr.uuid as *const [i8; DM_UUID_LEN] as *const [u8; DM_UUID_LEN]) };
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found array of 129 elements
   |
   = note: expected type `u8`
              found type `[i8; 129]`
error[E0606]: casting `&mut [u8; 128]` as `*mut [i8; 128]` is invalid
  --> src/dm.rs:81:29
   |
81 |             unsafe { &mut *(&mut hdr.name as *mut [i8; DM_NAME_LEN] as *mut [u8; DM_NAME_LEN]) };
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0606]: casting `&mut [u8; 129]` as `*mut [i8; 129]` is invalid
  --> src/dm.rs:88:29
   |
88 |             unsafe { &mut *(&mut hdr.uuid as *mut [i8; DM_UUID_LEN] as *mut [u8; DM_UUID_LEN]) };
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0606]: casting `&mut [u8]` as `*mut [i8]` is invalid
   --> src/dm.rs:449:33
    |
449 |                 unsafe { &mut *(&mut targ.target_type[..] as *mut [i8] as *mut [u8]) };
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0308]: mismatched types
   --> src/dm.rs:568:28
    |
568 |                         &*(&targ.target_type as *const [i8; 16] as *const [u8; 16]);
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found array of 16 elements
    |
    = note: expected type `u8`
               found type `[i8; 16]`
```

**Comment by mulkieran** [comment]
It looks eerily like a compiler error to me. The only way it can't be is if ```c_char``` is unsigned on these platforms, which would be radical.

**Comment by ignatenkobrain** [comment]
Let's fix this in the end in #343.
